version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/*.war ROOT.war
artifacts:
  files:
    - ROOT.war
    # - appspec.yml
  discard-paths: yes
